# Generated by Django 2.2 on 2023-07-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
